### ISSUE TITLE
Deleting Flights Doesn't Remove Clients?

### ISSUE THREAD

**Issue by Justintime50** [Thorium-Sim/thorium#2008] opened 2019-03-24 04:46 UTC
## Detailed Description

v1.2.5 or v1.2.6 - not sure as it's stuck somewhere in-between haha.

If I delete the flight and come back in, all the clients are still active even on a different sim and even though all those clients are no longer active on the network.

**Comment by alexanderson1993** [comment] 2019-03-26 02:05
As discussed on the Discord, this is by design, and I don't intend to change it anytime soon. Closing.

**Closed by alexanderson1993** 2019-03-26 02:05 UTC
